//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrMatrixNet.UnforgottenXSLT.SamplesRunner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MrMatrixNet.UnforgottenXSLT.SamplesRunner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity transform.
        /// </summary>
        internal static string Demo01 {
            get {
                return ResourceManager.GetString("Demo01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple navigation with for-each.
        /// </summary>
        internal static string Demo02 {
            get {
                return ResourceManager.GetString("Demo02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern matching to find attribute.
        /// </summary>
        internal static string Demo03 {
            get {
                return ResourceManager.GetString("Demo03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage of xsl:element to build content.
        /// </summary>
        internal static string Demo04 {
            get {
                return ResourceManager.GetString("Demo04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage of xsl:element and xsl:attribute to build content .
        /// </summary>
        internal static string Demo05 {
            get {
                return ResourceManager.GetString("Demo05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage xsl:value-of to select specific source value.
        /// </summary>
        internal static string Demo06 {
            get {
                return ResourceManager.GetString("Demo06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concat function with curly brackets.
        /// </summary>
        internal static string Demo07 {
            get {
                return ResourceManager.GetString("Demo07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First simple parameter as select.
        /// </summary>
        internal static string Demo08 {
            get {
                return ResourceManager.GetString("Demo08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First simple parameter as content.
        /// </summary>
        internal static string Demo09 {
            get {
                return ResourceManager.GetString("Demo09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex xml parameter.
        /// </summary>
        internal static string Demo10 {
            get {
                return ResourceManager.GetString("Demo10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First call to C# code.
        /// </summary>
        internal static string Demo11 {
            get {
                return ResourceManager.GetString("Demo11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injecting XML to html template.
        /// </summary>
        internal static string Demo12 {
            get {
                return ResourceManager.GetString("Demo12", resourceCulture);
            }
        }
    }
}
